# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testrunner.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='testrunner.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0ftestrunner.proto\"\x8b\x02\n\tHeartBeat\x12\x15\n\rheart_beat_id\x18\x01 \x01(\x05\x12#\n\x1bmachine_used_memory_percent\x18\x02 \x01(\x02\x12 \n\x18machine_used_cpu_percent\x18\x03 \x01(\x02\x12.\n\x0cprocess_list\x18\x04 \x03(\x0b\x32\x18.HeartBeat.ProcessParams\x1ap\n\rProcessParams\x12\x14\n\x0cprocess_name\x18\x01 \x01(\t\x12\x12\n\nprocess_id\x18\x02 \x01(\x05\x12\x17\n\x0fprocess_cmdline\x18\x03 \x01(\t\x12\x1c\n\x14process_memory_bytes\x18\x04 \x01(\x05\"#\n\x0bRun_Process\x12\x14\n\x0cprocess_path\x18\x01 \x01(\t\")\n\rPrint_Message\x12\x18\n\x10message_to_print\x18\x01 \x01(\t\"#\n\x0cKill_Process\x12\x13\n\x0bprocess_pid\x18\x01 \x01(\x05\"\xb7\x01\n\x11TestRunnerProtocol\x12\x18\n\x02HB\x18\x01 \x01(\x0b\x32\n.HeartBeatH\x00\x12#\n\x0brun_process\x18\x02 \x01(\x0b\x32\x0c.Run_ProcessH\x00\x12%\n\x0ckill_process\x18\x03 \x01(\x0b\x32\r.Kill_ProcessH\x00\x12#\n\tprint_msg\x18\x04 \x01(\x0b\x32\x0e.Print_MessageH\x00\x42\x17\n\x15OneOfSwitchSubMessageb\x06proto3'
)




_HEARTBEAT_PROCESSPARAMS = _descriptor.Descriptor(
  name='ProcessParams',
  full_name='HeartBeat.ProcessParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='process_name', full_name='HeartBeat.ProcessParams.process_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='process_id', full_name='HeartBeat.ProcessParams.process_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='process_cmdline', full_name='HeartBeat.ProcessParams.process_cmdline', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='process_memory_bytes', full_name='HeartBeat.ProcessParams.process_memory_bytes', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=287,
)

_HEARTBEAT = _descriptor.Descriptor(
  name='HeartBeat',
  full_name='HeartBeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heart_beat_id', full_name='HeartBeat.heart_beat_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='machine_used_memory_percent', full_name='HeartBeat.machine_used_memory_percent', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='machine_used_cpu_percent', full_name='HeartBeat.machine_used_cpu_percent', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='process_list', full_name='HeartBeat.process_list', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_HEARTBEAT_PROCESSPARAMS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=287,
)


_RUN_PROCESS = _descriptor.Descriptor(
  name='Run_Process',
  full_name='Run_Process',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='process_path', full_name='Run_Process.process_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=324,
)


_PRINT_MESSAGE = _descriptor.Descriptor(
  name='Print_Message',
  full_name='Print_Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_to_print', full_name='Print_Message.message_to_print', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=367,
)


_KILL_PROCESS = _descriptor.Descriptor(
  name='Kill_Process',
  full_name='Kill_Process',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='process_pid', full_name='Kill_Process.process_pid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=404,
)


_TestRunnerPROTOCOL = _descriptor.Descriptor(
  name='TestRunnerProtocol',
  full_name='TestRunnerProtocol',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='HB', full_name='TestRunnerProtocol.HB', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='run_process', full_name='TestRunnerProtocol.run_process', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kill_process', full_name='TestRunnerProtocol.kill_process', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='print_msg', full_name='TestRunnerProtocol.print_msg', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='OneOfSwitchSubMessage', full_name='TestRunnerProtocol.OneOfSwitchSubMessage',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=407,
  serialized_end=590,
)

_HEARTBEAT_PROCESSPARAMS.containing_type = _HEARTBEAT
_HEARTBEAT.fields_by_name['process_list'].message_type = _HEARTBEAT_PROCESSPARAMS
_TestRunnerPROTOCOL.fields_by_name['HB'].message_type = _HEARTBEAT
_TestRunnerPROTOCOL.fields_by_name['run_process'].message_type = _RUN_PROCESS
_TestRunnerPROTOCOL.fields_by_name['kill_process'].message_type = _KILL_PROCESS
_TestRunnerPROTOCOL.fields_by_name['print_msg'].message_type = _PRINT_MESSAGE
_TestRunnerPROTOCOL.oneofs_by_name['OneOfSwitchSubMessage'].fields.append(
  _TestRunnerPROTOCOL.fields_by_name['HB'])
_TestRunnerPROTOCOL.fields_by_name['HB'].containing_oneof = _TestRunnerPROTOCOL.oneofs_by_name['OneOfSwitchSubMessage']
_TestRunnerPROTOCOL.oneofs_by_name['OneOfSwitchSubMessage'].fields.append(
  _TestRunnerPROTOCOL.fields_by_name['run_process'])
_TestRunnerPROTOCOL.fields_by_name['run_process'].containing_oneof = _TestRunnerPROTOCOL.oneofs_by_name['OneOfSwitchSubMessage']
_TestRunnerPROTOCOL.oneofs_by_name['OneOfSwitchSubMessage'].fields.append(
  _TestRunnerPROTOCOL.fields_by_name['kill_process'])
_TestRunnerPROTOCOL.fields_by_name['kill_process'].containing_oneof = _TestRunnerPROTOCOL.oneofs_by_name['OneOfSwitchSubMessage']
_TestRunnerPROTOCOL.oneofs_by_name['OneOfSwitchSubMessage'].fields.append(
  _TestRunnerPROTOCOL.fields_by_name['print_msg'])
_TestRunnerPROTOCOL.fields_by_name['print_msg'].containing_oneof = _TestRunnerPROTOCOL.oneofs_by_name['OneOfSwitchSubMessage']
DESCRIPTOR.message_types_by_name['HeartBeat'] = _HEARTBEAT
DESCRIPTOR.message_types_by_name['Run_Process'] = _RUN_PROCESS
DESCRIPTOR.message_types_by_name['Print_Message'] = _PRINT_MESSAGE
DESCRIPTOR.message_types_by_name['Kill_Process'] = _KILL_PROCESS
DESCRIPTOR.message_types_by_name['TestRunnerProtocol'] = _TestRunnerPROTOCOL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeartBeat = _reflection.GeneratedProtocolMessageType('HeartBeat', (_message.Message,), {

  'ProcessParams' : _reflection.GeneratedProtocolMessageType('ProcessParams', (_message.Message,), {
    'DESCRIPTOR' : _HEARTBEAT_PROCESSPARAMS,
    '__module__' : 'testrunner_pb2'
    # @@protoc_insertion_point(class_scope:HeartBeat.ProcessParams)
    })
  ,
  'DESCRIPTOR' : _HEARTBEAT,
  '__module__' : 'testrunner_pb2'
  # @@protoc_insertion_point(class_scope:HeartBeat)
  })
_sym_db.RegisterMessage(HeartBeat)
_sym_db.RegisterMessage(HeartBeat.ProcessParams)

Run_Process = _reflection.GeneratedProtocolMessageType('Run_Process', (_message.Message,), {
  'DESCRIPTOR' : _RUN_PROCESS,
  '__module__' : 'testrunner_pb2'
  # @@protoc_insertion_point(class_scope:Run_Process)
  })
_sym_db.RegisterMessage(Run_Process)

Print_Message = _reflection.GeneratedProtocolMessageType('Print_Message', (_message.Message,), {
  'DESCRIPTOR' : _PRINT_MESSAGE,
  '__module__' : 'testrunner_pb2'
  # @@protoc_insertion_point(class_scope:Print_Message)
  })
_sym_db.RegisterMessage(Print_Message)

Kill_Process = _reflection.GeneratedProtocolMessageType('Kill_Process', (_message.Message,), {
  'DESCRIPTOR' : _KILL_PROCESS,
  '__module__' : 'testrunner_pb2'
  # @@protoc_insertion_point(class_scope:Kill_Process)
  })
_sym_db.RegisterMessage(Kill_Process)

TestRunnerProtocol = _reflection.GeneratedProtocolMessageType('TestRunnerProtocol', (_message.Message,), {
  'DESCRIPTOR' : _TestRunnerPROTOCOL,
  '__module__' : 'testrunner_pb2'
  # @@protoc_insertion_point(class_scope:TestRunnerProtocol)
  })
_sym_db.RegisterMessage(TestRunnerProtocol)


# @@protoc_insertion_point(module_scope)
